#ifndef HLSL_CPP_COMMON_TYPES
#define HLSL_CPP_COMMON_TYPES

// Light type
enum LIGHT_TYPE
{
    LIGHT_TYPE_DIRECTIONAL,
	LIGHT_TYPE_POINT,
	LIGHT_TYPE_COUNT
};

const static uint MAX_LIGHT_COUNT = 16;

#endif