#ifndef RAYTRACING_PROC_HLSL
#define RAYTRACING_PROC_HLSL

#include "Raytracing_common.hlsl"

struct MySphereIntersectionAttributes
{
    float3 Normal;
};

ConstantBuffer<CONSTANT_BUFFER_RT_PROC> l_ProcGeomCB : register(b1, space0);
StructuredBuffer<Sphere> g_Spheres : register(t0, space1);

[shader("intersection")]
void MyIntersectionShader_Sphere()
{
    float3 ro = ObjectRayOrigin();
    float3 rd = ObjectRayDirection();
    float tmin = max(RayTMin(), 1e-4);
    float tmax = RayTCurrent(); // FAR_PLANE 쓰면 다른 히트보다 먼 것도 리포트할 수 있음
    
    uint primitiveIndex = PrimitiveIndex();
    Sphere s = g_Spheres[primitiveIndex];

    float3 oc = ro - s.Center;
    float b = dot(oc, rd);
    float c = dot(oc, oc) - s.Radius * s.Radius;
    float d = b * b - c;

    if (d < 0.0)
        return;

    float sqrtD = sqrt(d);
    float t0 = -b - sqrtD; // enter
    float t1 = -b + sqrtD; // exit  (t0 <= t1 보장)

    if (t0 >= tmin && t0 <= tmax)
    {
        MySphereIntersectionAttributes a0;
        float3 p0 = ro + t0 * rd;
        a0.Normal = normalize(p0 - s.Center);
        ReportHit(t0, /*hitKind*/0, a0); // enter
    }
}


[shader("closesthit")]
void MyClosestHitShader_RadianceRay_Proc(inout RadiancePayload rayPayload, in MySphereIntersectionAttributes attr)
{
    float3 hitPosition = HitWorldPosition();
    uint instanceID = InstanceID(); // The instance ID as specified in the instance desc.
    uint systemInstanceIndex = InstanceIndex(); // The autogenerated index of the current instance in the top-level structure.
    
    float3 surfaceNormal = normalize(mul((float3x3) ObjectToWorld3x4(), attr.Normal));

    // Compute depth
    float4 projPos = mul(float4(hitPosition, 1.0), g_ViewProj);
    projPos /= projPos.w;
    rayPayload.depth = saturate(projPos.z);
    
    // Compute radiance
    BasicMaterial mtl = l_ProcGeomCB.Material;
    float3 baseColor = mtl.BaseColor;
    float metallic = mtl.MetallicFactor;
    float roughness = max(0.04f, saturate(mtl.RoughnessFactor));
    
    ShadingInfo info;
    info.Kd = (1.0 - mtl.MetallicFactor) * baseColor;
    info.Ks = saturate(lerp(mtl.SpecularColor, baseColor, metallic) * mtl.SpecularFactor);
    info.Kr = (metallic > 0.5) ? baseColor : 1.0.xxx;
    //info.Kr = float3(mtl.SpecularFactor, mtl.SpecularFactor, mtl.SpecularFactor);
    info.Kt = (1.0f - saturate(mtl.Opacity)) * baseColor;
    info.Roughness = roughness;
    info.AmbientOcclusionStrength = mtl.AmbientOcclusionStrength;
    
    rayPayload.radiance = Shade(rayPayload, surfaceNormal, hitPosition, info);
}

[shader("closesthit")]
void MyClosestHitShader_ShadowRay_Proc(inout ShadowPayload rayPayload, in MySphereIntersectionAttributes attr)
{
    // Never called if RAY_FLAG_ACCEPT_FIRST_HIT_AND_END_SEARCH is set.
    rayPayload.tHit = RayTCurrent();
}

#endif // RAYTRACING_HLSL
