#ifndef RAYTRACING_HLSL
#define RAYTRACING_HLSL

#include "Raytracing_common.hlsl"
#include "BxDF.hlsli"

// Local Root Parameter
ConstantBuffer<CONSTANT_BUFFER_RT_TRIGROUP> l_RayGeomCB : register(b1, space0);
StructuredBuffer<Vertex> l_Vertices : register(t0, space1);
ByteAddressBuffer l_Indices : register(t1, space1);
Texture2D<float4> l_DiffuseTexture : register(t2, space1);
Texture2D<float4> l_NormalTexture : register(t3, space1);

// Load three 16 bit indices.
static uint3 Load3x16BitIndices(uint offsetBytes)
{
    uint3 indices;

	// ByteAdressBuffer loads must be aligned at a 4 byte boundary.
	// Since we need to read three 16 bit indices: { 0, 1, 2 } 
	// aligned at a 4 byte boundary as: { 0 1 } { 2 0 } { 1 2 } { 0 1 } ...
	// we will load 8 bytes (~ 4 indices { a b | c d }) to handle two possible index triplet layouts,
	// based on first index's offsetBytes being aligned at the 4 byte boundary or not:
	//  Aligned:     { 0 1 | 2 - }
	//  Not aligned: { - 0 | 1 2 }
    const uint alignedOffset = offsetBytes & ~3;
    const uint2 four16BitIndices = l_Indices.Load2(alignedOffset);

	// Aligned: { 0 1 | 2 - } => retrieve first three 16bit indices
    if (alignedOffset == offsetBytes)
    {
        indices.x = four16BitIndices.x & 0xffff;
        indices.y = (four16BitIndices.x >> 16) & 0xffff;
        indices.z = four16BitIndices.y & 0xffff;
    }
    else // Notaligned: { - 0 | 1 2 } => retrieve last three 16bit indices
    {
        indices.x = (four16BitIndices.x >> 16) & 0xffff;
        indices.y = four16BitIndices.y & 0xffff;
        indices.z = (four16BitIndices.y >> 16) & 0xffff;
    }

    return indices;
}

[shader("raygeneration")]
void MyRaygenShader_RadianceRay()
{
    uint2 launchIndex = DispatchRaysIndex().xy;
    uint2 launchDim = DispatchRaysDimensions().xy;

    // Ray direction is computed by transforming the screen space coordinate to world space.
    float2 currPixel = float2(launchIndex.xy) + 0.5f; // center in the middle of the pixel.
    float2 resolution = float2(launchDim.xy);
    
    // Generate primary ray.
    float4 rayView = float4(
        ((currPixel.x / resolution.x) * 2.0f - 1.0f) / g_Proj._11,
        -((currPixel.y / resolution.y) * 2.0f - 1.0f) / g_Proj._22,
        1.0, 0.0);
    float4 rayDstWorld = mul(rayView, g_InvView);
    rayDstWorld.xyz = normalize(rayDstWorld.xyz);
    float3 worldDir = rayDstWorld.xyz;
    float3 worldOrigin = g_InvView._41_42_43; // Ray origin is the camera position.
    
    Ray ray =
    {
        worldOrigin,
		worldDir
    };
    
    // Trace primary ray.
    uint currRayRecursionDepth = 0;
    bool bCullNonOpaque = false;
    bool bCullBackFace = false;
    RadiancePayload rayPayload = TraceRadianceRay(ray, currRayRecursionDepth, g_MaxRadianceRayRecursionDepth, NEAR_PLANE, FAR_PLANE, bCullNonOpaque, bCullBackFace);
	
    // Output to the screen.
    g_OutputDiffuse[launchIndex.xy] = float4(rayPayload.radiance, 1);
    g_OutputDepth[launchIndex.xy] = rayPayload.depth;
}

[shader("closesthit")]
void MyClosestHitShader_RadianceRay(inout RadiancePayload rayPayload, in BuiltInTriangleIntersectionAttributes attr)
{
    float3 hitPosition = HitWorldPosition();
    uint instanceID = InstanceID(); // The instance ID as specified in the instance desc.
    uint systemInstanceIndex = InstanceIndex(); // The autogenerated index of the current instance in the top-level structure.
    
    uint baseIndex = PrimitiveIndex() * g_TriangleIndexStride; // The base index of the hit triangle's first 16 bit index.
    uint3 indices = Load3x16BitIndices(baseIndex);
    
    // Get vertex attributes.
    float2 vertexUV[3] =
    {
        l_Vertices[indices[0]].UV,
        l_Vertices[indices[1]].UV,
        l_Vertices[indices[2]].UV
    };
    float3 vertexNormal[3] =
    {
        l_Vertices[indices[0]].Normal,
        l_Vertices[indices[1]].Normal,
        l_Vertices[indices[2]].Normal
    };
    float3 vertexTangent[3] =
    {
        l_Vertices[indices[0]].Tangent,
        l_Vertices[indices[1]].Tangent,
        l_Vertices[indices[2]].Tangent
    };
    
    float2 texCoord = HitAttribute(vertexUV, attr);
    
    float4 texDiffuse = l_DiffuseTexture.SampleLevel(g_SamplerPoint, texCoord, 0);
    float3 texNormal = l_NormalTexture.SampleLevel(g_SamplerWrap, texCoord, 0).rgb;
    // float3 texNormal = float3(0.5, 0.5, 1.0);
    
    float3 localNormal = HitAttribute(vertexNormal, attr);
    float3 localTangent = HitAttribute(vertexTangent, attr);
    
    float3 worldNormal = normalize(mul(localNormal, (float3x3) ObjectToWorld4x3())); // TODO: like Standard.hlsl. use InverseTranspose?
    float3 worldTangent = normalize(mul(localTangent, (float3x3) ObjectToWorld4x3()));
    float3 worldBinormal = normalize(cross(worldTangent, worldNormal));
    
    float3 tanNormal = texNormal.rgb * 2.0 - 1.0;
    tanNormal.xy *= l_RayGeomCB.Material.NormalScale;
    tanNormal = normalize(tanNormal);
    
    float3 surfaceNormal = (tanNormal.xxx * worldTangent) + (tanNormal.yyy * worldBinormal) + (tanNormal.zzz * worldNormal);
    
    // Compute depth
    float4 projPos = mul(float4(hitPosition, 1.0), g_ViewProj);
    projPos /= projPos.w;
    rayPayload.depth = saturate(projPos.z);
    
    // Compute radiance
    BasicMaterial mtl = l_RayGeomCB.Material;
    float3 baseColor = mtl.BaseColor * texDiffuse.rgb;
    float metallic = mtl.MetallicFactor;
    float roughness = max(0.04f, saturate(mtl.RoughnessFactor));
    
    ShadingInfo info;
    info.Kd = (1.0 - mtl.MetallicFactor) * baseColor;
    info.Ks = saturate(lerp(mtl.SpecularColor, baseColor, metallic) * mtl.SpecularFactor);
    info.Kr = (metallic > 0.5) ? baseColor : 1.0.xxx;
    //info.Kr = float3(mtl.SpecularFactor, mtl.SpecularFactor, mtl.SpecularFactor);
    info.Kt = (1.0f - saturate(mtl.Opacity)) * baseColor;
    info.Roughness = roughness;
    info.AmbientOcclusionStrength = mtl.AmbientOcclusionStrength;
    
    rayPayload.radiance = Shade(rayPayload, surfaceNormal, hitPosition, info);
}

[shader("miss")]
void MyMissShader_RadianceRay(inout RadiancePayload rayPayload)
{
    float3 worldDir = normalize(WorldRayDirection());
    float3 skyColor = SampleSky(worldDir);
    float3 sunColor = EvaluateSun(worldDir);
    float3 L = skyColor + sunColor;
    
    rayPayload.radiance = L;
    // rayPayload.radiance = Tonemap_ACES(L); // TODO: remove tonemap from here and do it in the composition pass
    rayPayload.depth = 1.2;
}

[shader("anyhit")]
void MyAnyHitShader_RadianceRay(inout RadiancePayload payload, in BuiltInTriangleIntersectionAttributes attr)
{
    float3 hitPosition = HitWorldPosition();

    uint instanceID = InstanceID(); // The instance ID as specified in the instance desc.
    uint systemInstanceIndex = InstanceIndex(); // The autogenerated index of the current instance in the top-level structure.
    
    uint baseIndex = PrimitiveIndex() * g_TriangleIndexStride; // The base index of the hit triangle's first 16 bit index.
    
    // Load up 3 16 bit indices for the triangle.
    uint3 indices = Load3x16BitIndices(baseIndex);
    float2 texCoord[3] =
    {
        l_Vertices[indices[0]].UV,
        l_Vertices[indices[1]].UV,
        l_Vertices[indices[2]].UV
    };
    float2 currTexCoord = HitAttribute(texCoord, attr);
    float4 texDiffuse = l_DiffuseTexture.SampleLevel(g_SamplerPoint, currTexCoord, 0);
    float alpha = texDiffuse.a;
    
    if (alpha < ALPHA_TEST_THRESHOLD)
    {
        IgnoreHit();
    }
}

[shader("closesthit")]
void MyClosestHitShader_ShadowRay(inout ShadowPayload rayPayload, in BuiltInTriangleIntersectionAttributes attr)
{
    // Never called if RAY_FLAG_ACCEPT_FIRST_HIT_AND_END_SEARCH is set.
    rayPayload.tHit = RayTCurrent();
}
	
[shader("miss")]
void MyMissShader_ShadowRay(inout ShadowPayload rayPayload)
{
    // hit이벤트가 발생하지 않는다면(충돌하는 매시가 없다면 rayPayload.tHit = 0이 된다.
    rayPayload.tHit = HitDistanceOnMiss;
}

[shader("anyhit")]
void MyAnyHitShader_ShadowRay(inout ShadowPayload rayPayload, in BuiltInTriangleIntersectionAttributes attr)
{
    float3 hitPosition = HitWorldPosition();

	// Get the base index of the triangle's first 16 bit index.
    uint instanceID = InstanceID();
    uint systemInstanceIndex = InstanceIndex(); // The autogenerated index of the current instance in the top-level structure.
    
    uint baseIndex = PrimitiveIndex() * g_TriangleIndexStride; // The base index of the hit triangle's first 16 bit index.
    
    // Load up 3 16 bit indices for the triangle.
    uint3 indices = Load3x16BitIndices(baseIndex);
    float2 texCoord[3] =
    {
        l_Vertices[indices[0]].UV,
        l_Vertices[indices[1]].UV,
        l_Vertices[indices[2]].UV
    };
    float2 currTexCoord = HitAttribute(texCoord, attr);
    float4 texDiffuse = l_DiffuseTexture.SampleLevel(g_SamplerPoint, currTexCoord, 0);
    float alpha = texDiffuse.a;
    
    if (alpha < ALPHA_TEST_THRESHOLD)
    {
        IgnoreHit();
    }
    else
    {
        // Accept the hit and end search.
        // This is useful for alpha tested geometry.
        // It avoids invoking closest hit shader.
        // rayPayload.tHit = RayTCurrent();
        AcceptHitAndEndSearch();
    }
}

#endif // RAYTRACING_HLSL
