#ifndef RAYTRACING_PROC_HLSL
#define RAYTRACING_PROC_HLSL

#include "Raytracing_common.hlsl"

struct MyCasperIntersectionAttributes
{
    float3 Normal;
};

ConstantBuffer<CONSTANT_BUFFER_RT_PROC> l_ProcGeomCB : register(b1, space0);
TextureCube<float4> l_DiffuseAtlasTexture : register(t0, space1);
TextureCube<float4> l_DepthAtlasTexture : register(t1, space1);

float SafeRcp(float x)
{
    // 0 분모 방지: 기호를 보존한 작은 값으로 대체
    const float eps = 1e-8;
    return (abs(x) > eps) ? rcp(x) : ((x >= 0.0f) ? (1.0f / eps) : (-1.0f / eps));
}

[shader("intersection")]
void MyIntersectionShader_Casper()
{
    // 레이 (오브젝트 공간)
    const float3 ro = ObjectRayOrigin();
    const float3 rd = ObjectRayDirection(); // 정규화하지 말 것 (t 스케일 유지)

    float tminRay = max(RayTMin(), 1e-5);
    float tmaxRay = RayTCurrent();

    const float3 bmin = float3(-1.0, -1.0, -1.0);
    const float3 bmax = float3(1.0, 1.0, 1.0);

    float3 invRd = float3(SafeRcp(rd.x), SafeRcp(rd.y), SafeRcp(rd.z));
    float3 t0 = (bmin - ro) * invRd;
    float3 t1 = (bmax - ro) * invRd;
    float3 tmin3 = min(t0, t1);
    float tEnter = max(max(tmin3.x, tmin3.y), tmin3.z);

    float tHit = max(tEnter, tminRay);
    float3 enterPoint = ro + rd * tEnter;
    
    uint axisEnter = 0;
    if (abs(enterPoint.x) > 0.99 && abs(enterPoint.x) < 1.01)
        axisEnter = 0;
    if (abs(enterPoint.y) > 0.99 && abs(enterPoint.y) < 1.01)
        axisEnter = 1;
    if (abs(enterPoint.z) > 0.99 && abs(enterPoint.z) < 1.01)
        axisEnter = 2;
    
    uint axis = axisEnter;

    float3 n = float3(0, 0, 0);
    n[axis] = (rd[axis] >= 0.0f) ? -1.0f : 1.0f;

    // 리포트
    MyCasperIntersectionAttributes attr;
    attr.Normal = n; // object-space
    ReportHit(tHit, /*hitKind*/0, attr);
}


[shader("closesthit")]
void MyClosestHitShader_RadianceRay_Casper(inout RadiancePayload rayPayload, in MyCasperIntersectionAttributes attr)
{
    float3 hitPosition = HitWorldPosition();
    uint instanceID = InstanceID(); // The instance ID as specified in the instance desc.
    uint systemInstanceIndex = InstanceIndex(); // The autogenerated index of the current instance in the top-level structure.
    
    float3 hitObjectPosition = ObjectRayOrigin() + RayTCurrent() * ObjectRayDirection();
    float4 texDiffuse = l_DiffuseAtlasTexture.SampleLevel(g_SamplerClamp, normalize(hitObjectPosition), 0);
    
    float3 surfaceNormal = normalize(mul((float3x3) ObjectToWorld3x4(), attr.Normal));
    
    // Compute depth
    float4 projPos = mul(float4(hitPosition, 1.0), g_ViewProj);
    projPos /= projPos.w;
    rayPayload.depth = saturate(projPos.z);
    
    // Compute radiance
    BasicMaterial mtl = l_ProcGeomCB.Material;
    float3 baseColor = mtl.BaseColor * texDiffuse.xyz;
    float metallic = mtl.MetallicFactor;
    float roughness = max(0.04f, saturate(mtl.RoughnessFactor));
    
    ShadingInfo info;
    info.Kd = (1.0 - mtl.MetallicFactor) * baseColor;
    info.Ks = saturate(lerp(mtl.SpecularColor, baseColor, metallic) * mtl.SpecularFactor);
    info.Kr = (metallic > 0.5) ? baseColor : 1.0.xxx;
    //info.Kr = float3(mtl.SpecularFactor, mtl.SpecularFactor, mtl.SpecularFactor);
    info.Kt = (1.0f - saturate(mtl.Opacity)) * baseColor;
    info.Roughness = roughness;
    info.AmbientOcclusionStrength = mtl.AmbientOcclusionStrength;
    
    rayPayload.radiance = Shade(rayPayload, surfaceNormal, hitPosition, info);
}

[shader("closesthit")]
void MyClosestHitShader_ShadowRay_Casper(inout ShadowPayload rayPayload, in MyCasperIntersectionAttributes attr)
{
    // Never called if RAY_FLAG_ACCEPT_FIRST_HIT_AND_END_SEARCH is set.
    rayPayload.tHit = RayTCurrent();
}

#endif // RAYTRACING_HLSL
