#ifndef RAYTRACING_PROC_HLSL
#define RAYTRACING_PROC_HLSL

#include "Raytracing_common.hlsl"

struct MyCasperIntersectionAttributes
{
    float3 UnitSpaceHitPosition;
};

ConstantBuffer<CONSTANT_BUFFER_RT_PROC> l_ProcGeomCB : register(b1, space0);
TextureCube<float4> l_DiffuseAtlasTexture : register(t0, space1);
TextureCube<float> l_DepthAtlasTexture : register(t1, space1);

struct AABB
{
    float3 Min;
    float3 Max;
};
StructuredBuffer<AABB> l_AABBBuffer : register(t2, space1);

// =======================================================
// Unit-space helpers
// =======================================================

float RayTEnter()
{
    AABB aabb = l_AABBBuffer[PrimitiveIndex()];
    float3 origin = ObjectRayOrigin();
    float3 invDir = 1.0 / ObjectRayDirection();
    
    float3 t0 = (aabb.Min - origin) * invDir;
    float3 t1 = (aabb.Max - origin) * invDir;
    float3 tMin3 = min(t0, t1);
    
    return max(max(tMin3.x, tMin3.y), tMin3.z);
}

float RayTExit()
{
    AABB aabb = l_AABBBuffer[PrimitiveIndex()];
    float3 origin = ObjectRayOrigin();
    float3 invDir = 1.0 / ObjectRayDirection();
    
    float3 t0 = (aabb.Min - origin) * invDir;
    float3 t1 = (aabb.Max - origin) * invDir;
    float3 tMax3 = max(t0, t1);
    
    return min(min(tMax3.x, tMax3.y), tMax3.z);
}

float3 UnitRayDirection()
{
    AABB aabb = l_AABBBuffer[PrimitiveIndex()];
    float3 extent = aabb.Max - aabb.Min;
    float3 invExtent = 1.0 / extent;
    return ObjectRayDirection() * invExtent;
}

float3 UnitSpaceHitPosition()
{
    AABB aabb = l_AABBBuffer[PrimitiveIndex()];
    float3 objectHitPosition = ObjectRayOrigin() + RayTEnter() * ObjectRayDirection();
    float3 extent = aabb.Max - aabb.Min;
    float3 invExtent = 1.0 / extent;
    return (objectHitPosition - aabb.Min) * invExtent;
}

float3 UnitSpaceExitPosition()
{
    AABB aabb = l_AABBBuffer[PrimitiveIndex()];
    float3 objectExitPosition = ObjectRayOrigin() + RayTExit() * ObjectRayDirection();
    float3 extent = aabb.Max - aabb.Min;
    float3 invExtent = 1.0 / extent;
    return (objectExitPosition - aabb.Min) * invExtent;
}

float ComputeTHit(float3 unitSpacePos)
{
    AABB aabb = l_AABBBuffer[PrimitiveIndex()];
    float3 extent = aabb.Max - aabb.Min;
    float3 objectSpacePos = aabb.Min + unitSpacePos * extent;
    
    float3 rayOrigin = ObjectRayOrigin();
    float3 rayDir = ObjectRayDirection();
    
    float3 toPos = objectSpacePos - rayOrigin;
    float tHit = dot(toPos, rayDir) / dot(rayDir, rayDir);
    return tHit;
}

float2 GetLimits(float3 unitPos, int axis)
{
    float3 ndcPos = unitPos * 2.0f - 1.0f; // [0,1] -> [-1,1]
    
    float3 sampleDirNegative = ndcPos;
    sampleDirNegative[axis] = -1.0f;
    float negativeLimit = l_DepthAtlasTexture.SampleLevel(g_SamplerClamp, normalize(sampleDirNegative), 0);
    
    float3 sampleDirPositive = ndcPos;
    sampleDirPositive[axis] = 1.0f;
    float positiveLimit = l_DepthAtlasTexture.SampleLevel(g_SamplerClamp, normalize(sampleDirPositive), 0);
    
    return float2(negativeLimit, 1.0 - positiveLimit);
}

bool IsInsideGeometry(float3 unitPos)
{
    float2 limits[3];
    limits[0] = GetLimits(unitPos, 0);
    limits[1] = GetLimits(unitPos, 1);
    limits[2] = GetLimits(unitPos, 2);
    
    bool bInsideX = (limits[0].x <= unitPos.x) && (unitPos.x <= limits[0].y);
    bool bInsideY = (limits[1].x <= unitPos.y) && (unitPos.y <= limits[1].y);
    bool bInsideZ = (limits[2].x <= unitPos.z) && (unitPos.z <= limits[2].y);
    
    return bInsideX && bInsideY && bInsideZ;
}

// =======================================================
// Intersection Shader
// =======================================================

[shader("intersection")]
void MyIntersectionShader_Casper()
{
    float3 rayDir = UnitRayDirection();
    float3 enter = UnitSpaceHitPosition();
    float3 exit = UnitSpaceExitPosition();
    
    float tEnter = 0.0f;
    float tExit = length(exit - enter) / max(length(rayDir), 1e-8);
    
    const int MAX_STEPS = 128;
    float dt = max((tExit - tEnter) / MAX_STEPS, 1e-5);
    
    float tCurr = 0.0;
    float3 currPos = enter + tCurr * rayDir;
    
    for (int stepCount = 0; stepCount < MAX_STEPS; ++stepCount)
    {
        if (IsInsideGeometry(currPos))
        {
            MyCasperIntersectionAttributes attr;
            attr.UnitSpaceHitPosition = currPos;
            float tHit = ComputeTHit(currPos);
    
            ReportHit(tHit, /*hitKind*/0, attr);
            return;
        }

        tCurr += dt;
        currPos = enter + tCurr * rayDir;
    }
}

[shader("closesthit")]
void MyClosestHitShader_RadianceRay_Casper(inout RadiancePayload rayPayload, in MyCasperIntersectionAttributes attr)
{
    float3 hitPosition = HitWorldPosition();
    uint instanceID = InstanceID(); // The instance ID as specified in the instance desc.
    uint systemInstanceIndex = InstanceIndex(); // The autogenerated index of the current instance in the top-level structure.
    
    // Compute depth
    float4 projPos = mul(float4(hitPosition, 1.0), g_ViewProj);
    projPos /= projPos.w;
    rayPayload.depth = saturate(projPos.z);
    
    float tt = RayTCurrent().xxx / 20.0;
    rayPayload.radiance = tt * tt;
    return;
    
    float3 hitObjectPosition = ObjectRayOrigin() + RayTCurrent() * ObjectRayDirection();
    float3 localtion = attr.UnitSpaceHitPosition * 2.0f - 1.0f; // [0,1] -> [-1,1]
    float4 texDiffuse = l_DiffuseAtlasTexture.SampleLevel(g_SamplerClamp, localtion, 0);
    float texDepth = l_DepthAtlasTexture.SampleLevel(g_SamplerClamp, localtion, 0);
    
    float3 objectNormal = float3(0, 0, 1); // TODO: Compute proper normal 
    float3 surfaceNormal = normalize(mul((float3x3) ObjectToWorld3x4(), objectNormal));
    
    // Compute radiance
    BasicMaterial mtl = l_ProcGeomCB.Material;
    float3 baseColor = mtl.BaseColor * texDiffuse.xyz;
    float metallic = mtl.MetallicFactor;
    float roughness = max(0.04f, saturate(mtl.RoughnessFactor));
    
    ShadingInfo info;
    info.Kd = (1.0 - mtl.MetallicFactor) * baseColor;
    info.Ks = saturate(lerp(mtl.SpecularColor, baseColor, metallic) * mtl.SpecularFactor);
    info.Kr = (metallic > 0.5) ? baseColor : 1.0.xxx;
    //info.Kr = float3(mtl.SpecularFactor, mtl.SpecularFactor, mtl.SpecularFactor);
    info.Kt = (1.0f - saturate(mtl.Opacity)) * baseColor;
    info.Roughness = roughness;
    info.AmbientOcclusionStrength = mtl.AmbientOcclusionStrength;
    
    rayPayload.radiance = Shade(rayPayload, surfaceNormal, hitPosition, info);
}

[shader("closesthit")]
void MyClosestHitShader_ShadowRay_Casper(inout ShadowPayload rayPayload, in MyCasperIntersectionAttributes attr)
{
    // Never called if RAY_FLAG_ACCEPT_FIRST_HIT_AND_END_SEARCH is set.
    rayPayload.tHit = RayTCurrent();
}

#endif // RAYTRACING_HLSL
